### ISSUE TITLE
Valeur de remplacement

### ISSUE THREAD

**Issue by adriacousmie** [RobertManager/robert#18]
La valeur de remplacement ne prend pas en compte les quantité de matériel. Ex: Je loue seulement 4 micros qui valent chacun 100€, Robert affiche 100€ dans la case "val. remp." du devis. C'est déjà quelque chose de pas très clair (qui mériterait surement une petite \* avec explication) mais si en plus on affiche pas le bon chiffre

**Comment by polosson** [comment]
Voilà, après quelques minutes (années !!), voilà le bug corrigé. Cheers !!
