### ISSUE TITLE
Bug Impression 

### ISSUE THREAD

**Issue by Ptijean** [RobertManager/robert#22]
Bonjour,

J'ai un problème lorsque je veux éditer un devis ou facture, ainsi que pour l'imprimer.
Le devis/facture se crée bien, mais quand je veux faire un aperçu de celui-ci, j'ai un immense code qui s'affiche avec des hiéroglyphes (je vous ait joint la photo).
Est-ce une erreur de ma part dans le MySQL, ou pas ?

Je vous remercie d'avance.
![capture decran 2014-05-09 a 17 25 30](https://cloud.githubusercontent.com/assets/7535436/2930071/2be190dc-d791-11e3-8257-afa2b65605d6.png)

**Comment by polosson** [comment]
Ce bug semble lié au navigateur ou à l'OS, et ne pourra être résolu dans cette version.
