### ISSUE TITLE
Impression récap

### ISSUE THREAD

**Issue by ALC79** [RobertManager/robert#25]
Bonjour,

J'ai installé le robert sur 2 machines 1 windows7 et 1 linux UBUNTU
Tout marche a merveille pour l'instant sauf une fonction.

Après avoir crée un plan je souhaite imprimer le récap comme le robert le propose mais là: bug!! J'ai le message suivant qui s'affiche dans une nouvelle fenêtre

Le ROBERT sous windows:
Fatal error: Call-time pass-by-reference has been removed in C:\Program Files (x86)\EasyPHP-DevServer-13.1VC9\data\localweb\robert-master\modals\plan_printRecap.php on line 261
Le ligne 261 est celle ci : Matos_getManque ( $retour['id'], &$retour['matos']);

Le ROBERT sous linux:
pas de message d'erreur mais Page blanche dans la nouvelle fenêtre

Avez vous une idée?

Merci

**Comment by polosson** [comment]
Toujours pas confirmé ni reporté par d'autres personnes, on ferme.
