### ISSUE TITLE
Affichage Calendrier

### ISSUE THREAD

**Issue by Pilou6t6** [RobertManager/robert#26]
Bonjour,

Tout mes événements ce place à gauche dans le calendrier et non sous le Jour correspondant à celui ci. 

Une solution?
Après vérification, cela le fait uniquement sur mon MacBook Pro sur Safari...

**Comment by polosson** [comment]
Ce bug est trop lié à Safari sous Mac, et depuis le temps peut-être que Safari a été mis à jour... nous ne donnerons donc pas suite, faute de pouvoir tester plus. On ferme !
