### ISSUE TITLE
Données effacées à chaque changement de page

### ISSUE THREAD

**Issue by fabiensimoens** [RobertManager/robert#31]
Bonjour, je vous contacte car je viens d'installer votre interface web de gestion et suis face à un problème que je n'ai pas vu dans la démo. En effet, à chaque chargement d'une nouvelle page, les données de la page précédente sont effacées. Par exemple pour la création d'un évènement la date est effacée lorsque l'on passe à la page de choix des techniciens. Auriez-vous une explication à ce problème ? Par avance, merci à vous.

**Comment by polosson** [comment]
Toujours pas confirmé ni reporté par d'autres personnes, on ferme, désolé !
