### ISSUE TITLE
Bug sur mon petit site

### ISSUE THREAD

**Issue by easipc94** [RobertManager/robert#34]
Bonjour, 

Je teste votre logiciel et ai fait les importations et modif demandées mais j'ai cette erreur qui apparait dès que j'ajoute un tech sur un plan et même chose quand je met du matériel. 

ERREUR JSON : Invalid JSON:
<b>Warning</b>:  implode() [<a href='function.implode'>function.implode</a>]: Invalid arguments passed in <b>/fct/plans_actions.php</b> on line <b>366</b>
{"error":"OK"}

Avez vous une idée ?
Merci d'avance
Stéphane

**Comment by polosson** [comment]
Bonjour,
Ce qui est étrange c'est que la fonction "implode" en question ne se trouve pas à la ligne 366, mais 363... Êtes-vous certain d'avoir installé une version à jour du Robert ?
Si oui, avez-vous fait des modifications dans le code source ?
Avez-vous ajouté des techniciens dans la partie "gens" ?
Merci de spécifier aussi quelle version de php avez-vous côté serveur.

**Comment by easipc94** [comment]
Bonjour,

 

Comme j’ai eu des problèmes j’ai essayé qq modifs.

 

J’ai remis le fichier de base et ai bien le problème sur la ligne 363

 

Le problème survient la première fosi quand je selectionne le tech (Gens) j’ai le message qui apparait.

 

Coté serveur PHP 5.2

 

Le lien est http://www.luxe-transport.com/phpinfo.php

 

Merci d’avance.

 

Sur ce site j’ai remis le site de base.

 

Stéphane

 

De : Paul MAILLARDET [mailto:notifications@github.com] 
Envoyé : dimanche 11 janvier 2015 12:51
À : RobertManager/robert
Cc : easipc94
Objet : Re: [robert] Bug sur mon petit site (#34)

 

Bonjour,
Ce qui est étrange c'est que la fonction "implode" en question ne se trouve pas à la ligne 366, mais 363... Êtes-vous certain d'avoir installé une version à jour du Robert ?
Si oui, avez-vous fait des modifications dans le code source ?
Avez-vous ajouté des techniciens dans la partie "gens" ?
Merci de spécifier aussi quelle version de php avez-vous côté serveur.

**Comment by polosson** [comment]
Je me suis permis de faire des essais sur votre site, et je ne comprend vraiment pas pourquoi la fonction "implode" plante. Cela est peut-être dû à la ligne précédente (le décodage json) mais sans accès à votre serveur directement je ne peux pas faire grand chose niveau débogage.
Vous êtes le seul à qui une telle chose arrive, aussi je ne peux confirmer le bug comme venant du code source... Cela peut-être un problème lié à la configuration de votre serveur.

**Comment by easipc94** [comment]
Le problème est que ce n’est pas un serveur propre mais un hébergement de site web. Je n’ai pas accès au serveur directement.

 

Juste à Phpmyadmin c’est tout

 

Peut-être devrais-je monter un serveur php mysql 

 

J’utilise sur un autre site un nas synology . qu’en pensez-vous de cette solution. Le serveur SQL est mariaDB

 

Bonne soirée

 

De : Paul MAILLARDET [mailto:notifications@github.com] 
Envoyé : lundi 12 janvier 2015 15:41
À : RobertManager/robert
Cc : easipc94
Objet : Re: [robert] Bug sur mon petit site (#34)

 

Je me suis permis de faire des essais sur votre site, et je ne comprend vraiment pas pourquoi la fonction "implode" plante. Cela est peut-être dû à la ligne précédente (le décodage json) mais sans accès à votre serveur directement je ne peux pas faire grand chose niveau débogage.
Vous êtes le seul à qui une telle chose arrive, aussi je ne peux confirmer le bug comme venant du code source... Cela peut-être un problème lié à la configuration de votre serveur.

**Comment by easipc94** [comment]
J’ai eu l’hébergeur, il m’a transmis un lien qui permet de voir les informations du serveur 

 

http://demo.online.net/

 

merci de votre aide

 

 

 

De : Paul MAILLARDET [mailto:notifications@github.com] 
Envoyé : lundi 12 janvier 2015 15:41
À : RobertManager/robert
Cc : easipc94
Objet : Re: [robert] Bug sur mon petit site (#34)

 

Je me suis permis de faire des essais sur votre site, et je ne comprend vraiment pas pourquoi la fonction "implode" plante. Cela est peut-être dû à la ligne précédente (le décodage json) mais sans accès à votre serveur directement je ne peux pas faire grand chose niveau débogage.
Vous êtes le seul à qui une telle chose arrive, aussi je ne peux confirmer le bug comme venant du code source... Cela peut-être un problème lié à la configuration de votre serveur.

**Comment by polosson** [comment]
Peut-être que le souci viens du fait que votre hébergement mutualisé actuel utilise la version 5.2 de php. Je vous suggère de demander à votre hébergeur s'il est possible pour vous de changer la version de php en 5.5 ou supérieur. Cela pourra peut-être régler le souci...
Sinon, je ne vois pas ! Et nous n'avons pas suffisamment de financement actuellement pour continuer le développement du Robert... Désolé de ne pas avoir pu résoudre votre problème.

**Comment by easipc94** [comment]
Bonjour

Sur l hébergement, c est en 5.4 pour l instant.  Pas d amélioration de ce côté.  Je vais vous pour tester sur un autre hébergement.  


Par contre, une question :

Peux t on utiliser ce logiciel pour de la location de véhicules.  Quand je fais le test sur un jour j'ai bien le transport mais sur plusieurs jours il ne compte qu une fois. 

Peux t on remédier à cela ? 


Stéphane RICHET

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Paul MAILLARDET <notifications@github.com> 
Date :13/01/2015  12:23  (GMT+01:00) 
A : RobertManager/robert <robert@noreply.github.com> 
Cc : easipc94 <stephane.richet@go-micro.fr> 
Objet : Re: [robert] Bug sur mon petit site (#34) 

Peut-être que le souci viens du fait que votre hébergement mutualisé actuel utilise la version 5.2 de php. Je vous suggère de demander à votre hébergeur s'il est possible pour vous de changer la version de php en 5.5 ou supérieur. Cela pourra peut-être régler le souci...
Sinon, je ne vois pas ! Et nous n'avons pas suffisamment de financement actuellement pour continuer le développement du Robert... Désolé de ne pas avoir pu résoudre votre problème.

**Comment by polosson** [comment]
Bonjour,

Le Robert n'est vraiment pas fait pour de la location de véhicule... Il a été conçu pour de la location de matériel de spectacle.
Ne disposant pas actuellement de financement pour développer le logiciel, nous ne pourrons donc pas faire d'adaptation pour ce domaine dans l'immédiat.
Merci de votre compréhension.

**Comment by polosson** [comment]
Sans suite, ni info complémentaire, ni demande similaire, on considère que le bug est résolu de lui-même.
