### ISSUE TITLE
Bug Sur calendrier

### ISSUE THREAD

**Issue by Jack3483** [RobertManager/robert#35]
Bonjour,

Je suis en train d'installer votre application sur mon serveur Ubuntu et voila le message que j'ai en affichant le calendrier : 
'Erreur Ajax ! vérifiez votre connexion à internet. Il se peut aussi que le serveur soit temporairement inaccessible... WTF!'

Je vois pas ou peut se situer le problème

Merci pour votre aide

**Comment by polosson** [comment]
Ce message apparaît généralement quand une requête Ajax ne peut aboutir, soit parce que le serveur est indisponible, soit parce que l'adresse de la requête est erronée, soit parce que votre connexion à internet n'est pas bonne.
Sans accès à votre installation, nous ne pouvons malheureusement rien faire...

**Comment by Jack3483** [comment]
Ok, merci, mais je suis en local. Sur un Ubuntu 12.04 LTS avec apache 2.4.12 et php 5.6.8

**Comment by Jack3483** [comment]
Bonjour,

Après maints essais, j'ai trouvé d'ou venait le problème. En l'absence de technicien crée, la requête ajax n'aboutie pas. J'ai crée un technicien, et le problème est résolu.

De plus, dans init-all-pages.js - Ligne 28, j'ai du rajouter  "event.keyCode == 59 ||" sinon il ne prenait pas en compte le séparateur décimal.

Merci pour votre boulot
