### ISSUE TITLE
Rajout des plages horaires sur l'agenda

### ISSUE THREAD

**Issue by Stephbalma** [RobertManager/robert#36]
Bonjour,

Serait possible de rajouter des plages horaires sur l'agenda?

Merci pour votre aide

Cordialement

Stéphane

**Comment by polosson** [comment]
Ce n'était pas prévu à la base, la journée étant la plus petit entité temporelle choisie pour le fonctionnement du Robert. En effet, il est destiné avant tout à la location de matériel pour les concerts, ce qui fait qu'un "plan" (une prestation) a peu de chance de ne durer que quelques heures.
Mais, dans l'absolu, c'est possible, oui. Simplement, nous ne ferons pas la modification nous-même, pour 2 raisons : par manque de financement, et parce que quelques structures intéressées sont en train de réunir un budget pour le Robert 2.0.
Cependant, vous pouvez tout à fait modifier le code source (faire un "fork") du Robert pour l'adapter à vos propres besoin.
