### ISSUE TITLE
Problème copier-coller en modification CGV Devis

### ISSUE THREAD

**Issue by FrankS13** [RobertManager/robert#37]
Bonjour,
Merci pour le travail amorcé la solution est très adaptée à la prestation. Ce que j'ai constaté c'est un bug lorsque l'on fait un copier-coller dans les CGV (pré requis) du devis. Les caractères accentués sont mal interprétés (é, ô, etc.).
Frank

**Comment by polosson** [comment]
Bonjour,
Merci pour vos retours, nous en tiendrons compte pour la prochaine version (Robert 2.0) dont le développement débutera dès que nous auront réuni les fonds suffisants.
Vous pourrez vous tenir informé, donner vos suggestions et discuter autour de cette prochaine version sur [le forum](http://robertforum.polosson.com/).

**Comment by AW2C** [comment]
Bonjour,

Je ne suis pas un utilisateur de Robert mais j'ai déjà eu ce genre de problème sur d'autres CMS (système de gestion de contenu).

La façon la plus rapide de contourner le problème est de copier/coller d'abord votre texte dans un éditeur de code (notepad++ sur windows, Fraise sur Mac, les deux sont gratuits normalement.) et de faire des recherche (ctrl + F) sur les caractères bizarre et de les remplacer. Attention vous pouvez remplacer tous les caractères identiques en une seule fois (find all : trouve les tous).

En espérant vous aidez ;-)

**Comment by polosson** [comment]
Il s'agit donc d'un bug relatif au système côté OS / navigateur, rien à voir avec Robert à priori.

**Comment by lawebfabric** [comment]
Quelle réactivité ! ^^
