### ISSUE TITLE
Modifier la Monnaie

### ISSUE THREAD

**Issue by annivzinal** [RobertManager/robert#41]
Bonjour,

nous somme un Office du tourisme en Suisse et souhaitons utiliser ce super logiciel pour la gestion de notre matériel. Cependant tous les prix sont en euros (logique en même temps). Comment faire pour changer la monnaie, supprimer n`de SIRET? 

Merci de votre réponse.

meilleures salutations

**Comment by polosson** [comment]
Bonjour,

Merci de votre intérêt pour le projet. Cette version de Robert n'est plus maintenue, car la version 2.0 est en préparation, et son développement débutera quand les fonds nécessaires auront été trouvés. En attendant, nous vous invitons à vous rendre sur [le forum](http://robertforum.polosson.com) pour voir les nouvelles fonctionnalités qui seront ajoutées à Robert 2, mais aussi proposer vos idées et envies pour cette prochaine version et donner votre avis sur divers sujet.
Vous pouvez aussi consulter [le site web officiel](http://robert.polosson.com/) et vous inscrire à [la newsletter](http://newsrobert.polosson.com/abo.php) pour vous tenir informés de l'avancement du projet.

Cependant j'ai quand même pris le temps de vous faire un patch qui vous permettra d'utiliser Robert en Francs Suisses. Ce patch vous sera utile si vous avez cloné Robert depuis github, mais inutile si vous avez simplement téléchargé Robert en Zip.

Si vous avez cloné Robert, vous pouvez [télécharger le patch à cette adresse](http://www.polosson.com/public/scripts/ROBERT-CHF-patch.zip), décompresser son contenu puis l'utiliser pour modifier le code source du robert grâce à la commande Git suivante (en vous plaçant avec un terminal dans le dossier contenant le code source de Robert) :
`git apply /chemin/vers/le/fichier/ROBERT_0.5-CHF.patch`

En revanche si vous avez téléchargé Robert en Zip, faites le moi savoir et je vous fournirai le code source complet modifié.

**Comment by annivzinal** [comment]
Bonjour,
 
un grand merci pour votre réponse très rapide.
 
Pour la version, j'ai effectivement téléchargé la version Zip car pour l'instant on le teste en local (easyphp).
 
Merci beaucoup.
 
Yanis Chauvel
 

 
Date: Fri, 13 May 2016 16:01:16 -0700

**Comment by polosson** [comment]
OK, j'ai créé une branche "CHF", ainsi que la release correspondante, que vous pouvez télécharger ici :
[github.com/RobertManager/robert/releases/tag/v0.5-CHF](https://github.com/RobertManager/robert/releases/tag/v0.5-CHF)

N'oubliez pas de modifier le fichier `config/common.inc` pour l'accès à la base de données.
