### ISSUE TITLE
Rajouter l'heure aux événements 

### ISSUE THREAD

**Issue by xcrocfer** [RobertManager/robert#44]
Nous aimerions pouvoir rajouter l'heure sur le calendrier pour les débuts et les fins de manifestations

Cordialement,

Xavier Crocfer

**Comment by polosson** [comment]
Bonjour Xavier,

Il est déjà prévu d'intégrer un calendrier horaire à la version 2.0 de Robert. Pour cela nous utiliserons le [module "Plantt"](http://www.code.polosson.com/Plantt/) qui a déjà été développé spécialement pour cette fonction. Ce module n'est cependant pas compatible avec la première version de Robert, donc il faudra attendre la sortie de la version 2.0 pour avoir cette fonctionnalité.
Nous sommes toujours en recherche de financement pour le développement de cette deuxième version, et bientôt une campagne de financement participatif sera lancée. Je vous invite à vous abonner à [la newsletter](http://newsrobert.polosson.com/abo.php) pour vous tenir informé de l'évolution de ce projet.
Cordialement,
.P

**Comment by xcrocfer** [comment]
Bonjour Paul,

Merci pour votre réponse rapide, cela est dommage. Avez-vous de la visibilité sur la sortie de la version 2.0 ? J’ai bien compris que vous êtes en recherche de financement mais j’espère que vous pourrez m’éclairer sur ce point.

Excellente fin de journée à vous.

Bien cordialement,


[signature xcrocfer]



De : Paul MAILLARDET [mailto:notifications@github.com]
Envoyé : vendredi 16 septembre 2016 17:13
À : RobertManager/robert
Cc : Xavier Crocfer; Author
Objet : Re: [RobertManager/robert] Rajouter l'heure aux événements (#44)


Bonjour Xavier,

Il est déjà prévu d'intégrer un calendrier horaire à la version 2.0 de Robert. Pour cela nous utiliserons le module "Plantt"<http://www.code.polosson.com/Plantt/> qui a déjà été développé spécialement pour cette fonction. Ce module n'est cependant pas compatible avec la première version de Robert, donc il faudra attendre la sortie de la version 2.0 pour avoir cette fonctionnalité.
Nous sommes toujours en recherche de financement pour le développement de cette deuxième version, et bientôt une campagne de financement participatif sera lancée. Je vous invite à vous abonner à la newsletter<http://newsrobert.polosson.com/abo.php> pour vous tenir informé de l'évolution de ce projet.
Cordialement,
.P
