### ISSUE TITLE
Mes devis ressemblent à du code 

### ISSUE THREAD

**Issue by techniscene42** [RobertManager/robert#45]
bonjour,
Voici a quoi ressemble le devis à partir du logiciel:

%PDF-1.3 3 0 obj <> endobj 4 0 obj <> stream x��Y�n��}����@ ����������������������������������
(et ainsi de suite...)

Merci d'avance

**Comment by moutew** [comment]
Bonjour,

Il nous faudrait plus de détails sur l'environnement d'installation de Robert ( OS, version php ).
Avez vous essayé avec plusieurs navigateurs ?

**Comment by k0** [comment]
Bonjour... je ne sais pas pourquoi je suis en cet thread mais je vous souet
bonne chance !

2016-12-29 14:11 GMT+01:00 moutew <notifications@github.com>:

**Comment by polosson** [comment]
Bonjour !
On dirait que la sortie est bien encodée en PDF... Avez-vous essayé d'enregistrer la sortie vers un fichier qui a l'extension ".pdf", puis de l'ouvrir avec un lecteur PDF ?

**Comment by moutew** [comment]
@polosson : J'ai essayé de mon coté, ça ne marche pas, sous Linux en tout cas. Il me semble qu'on avait déjà eu le pb, mais dur de me rapeller pourquoi ;(
Histoire d'en tête de la réponse, mimetype ... I can't rememner !

@techniscene42, cela vous est affiché à quel moment ? Vous cliquez sur télécharger le devis/facture ? Est ce que l'affichage des 'codes' se fait dans la fenêtre navigateur ou bien vous avez un nouveau fichier téléchargé ? Je suppose que vous avez un lecteur PDF ;)

**Comment by techniscene42** [comment]
Salut à tous
Alors je tourne sous Windows 7, j'ai essayé sous divers navigateur (chrome,IE,firefox), mon robert est installé sur un serveur 1&1 sous linux (de mémoire) et ma version PHP est 5.6.
@moutew Ceci arrive juste après la création de mon devis ou quand je clique sur le liens du fameux devis / facture.
l'affichage des code se fait en fenêtre navigateur. Bien sur j'ai acrobat reader d'installé
@polosson Mon devis est généré quand même, si je vais le chercher dans le dossier datas je peut l'ouvrir mais pas à partir de robert ....

merci pour votre aide

**Comment by polosson** [comment]
Ah ok, donc il semblerai que ça soit une histoire de config Windows (mauvaise gestion des types Mime ?)... Et là, perso je ne peux pas trop aider.
Ce que tu peux faire en attendant, c'est un clic-droit sur le lien du devis, puis cliquer sur "enregistrer la cible du lien sous..." pour récupérer le fichier en local et l'ouvrir avec Acrobat Reader.
Si jamais tu trouves le problème, n'hésites pas à en faire part aux autres par ici, ou sur [le forum](http://robertforum.polosson.com) !
Cheers

**Comment by techniscene42** [comment]
@polosson Meme en faisant clic droit il m'enregistre une page web et non mon pdf .... :-(

**Comment by polosson** [comment]
Owkay,
peux-tu nous donner un exemple du lien que Robert te génère ?

**Comment by polosson** [comment]
Et, dernière piste...
Est-ce qu'il y a un point (.) dans le nom du fichier généré ?

**Comment by techniscene42** [comment]
nom du fichier:Devis_Techniscene42_20161229-1_techniscene42.pdf
la ou pointe le lien : http://intranet.techniscene42.fr/fct/downloader.php?dir=PlanDevis&planID=3&file=Devis_Techniscene42_20161229-1_techniscene42.pdf

**Comment by polosson** [comment]
OK merci.
Chez moi le navigateur n'affiche strictement rien (page blanche), donc il doit y avoir une erreur de config serveur quelque part... Désolé mais là je ne vois pas trop d'où peut venir le souci.

L'idéal serait que vous ayez accès aux logs des erreurs Apache du serveur, pour voir si il y a des notices ou des warnings qui pourraient nous éclairer sur la situation. Si ce n'est pas possible, il faudrait modifier le fichier `fct/downloader.php` pour qu'il affiche les erreurs (ajouter la ligne `error_reporting(E_ALL);` au début du fichier), ou même modifier le php.ini du serveur (voir sur votre espace client 1&1) pour qu'il affiche toutes les erreurs.

Sans infos complémentaire, nous ne pourrons pas vous aider mieux.

PS: j'ai édité votre dernière réponse en changeant le domaine du lien pour des raisons de sécurité (on sait jamais).

**Comment by techniscene42** [comment]
merci pour la modif de serveur :-).
voici les erreur affichés 
Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in classes/Connecting.class.php on line 239

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in /classes/Connecting.class.php on line 240

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in classes/Connecting.class.php on line 241

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in fct/downloader.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in fct/downloader.php on line 62

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in /fct/downloader.php on line 63

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in fct/downloader.php on line 64

Warning: Cannot modify header information - headers already sent by (output started at config/common.inc:1) in fct/downloader.php on line 65

Notice: ob_clean(): failed to delete buffer. No buffer to delete in /fct/downloader.php on line 70

**Comment by polosson** [comment]
Ok, c'est vraiment bizarre.
Avez-vous modifié un des fichiers cités ? Ajouté un quelconque `header()` ou un `echo` quelque part ?
Là j'aurai même tendance à dire qu'il s'agit d'un espace ou d'une ligne vide tout en haut du fichier `config/common.inc`, avant l'ouverture de balise `<?php`. Assurez-vous que cette balise est la toute première chose du fichier (à la première ligne, première colonne ; pas d'espace ni de ligne vierge avant), et réessayez pour voir.
Sinon, je vois pas d'où ça peut venir et vous encourage à réinstaller Robert entièrement à partir de la dernière version de GitHub.

**Comment by polosson** [comment]
Sans info complémentaire, on estime que le bug est résolu. Cheers !
