### ISSUE TITLE
Problème d'installation en intranet

### ISSUE THREAD

**Issue by Herve33** [RobertManager/robert#48]
Bonjour,

nous sommes un établissement de formation audiovisuel au sein d'un groupe scolaire et notre service informatique peine à installer votre appli.

Voici le message que m'a envoyé la personne chargée de l'installer:

"Après des tests simples sur une machine indépendante, j'ai encore un peu peiné pour qu'elle fonctionne sur notre serveur Windows.

Je souhaiterais que vous fassiez vous-même des tests fonctionnels avant que d'envisager un accès depuis l'extérieur.

Je ne suis pas tellement confiant parce que j'ai déjà dû intervenir sur le schéma de la base de données pour pouvoir créer votre compte utilisateur  parce que des champs n'avaient pas de valeur par défaut (en mettant NULL par défaut, je n'ai peut-être que repoussé le problème...). J'ai aussi vu une erreur concernant "Ajax" (peut-être un problème de configuration)."

Je me suis donc mis à des tests d'utilisation et je ne parvenais pas à créer de nouvelles entrées dans les différents menus (matériel, techniciens, bénéficiaires) des messages d'erreur me sont apparus à chaque fois.

Merci pour votre aide.

**Comment by moutew** [comment]
Bonjour,
Pouvez vous nous indiquer votre environnement serveur / base de donnée ?
Je me souviens d'un cas similaire sous windows, la base de donnée de départ était mal importée, certains champs pouvant être NULL n'étaient pas configurés comme tel. Le fonctionement avec cette BDD non conforme était hasardeux. Cela ressemble à votre problème.
Aucun lien à priori avec une config en intranet.

**Comment by Herve33** [comment]
Bonjour,


Merci beaucoup pour votre retour, je vais transférer votre mail notre
responsable du service informatique qui se chargera de vous répondre ou me
répondra et je continuerai de faire l'intermédiaire!

Bonne journée



Cordialement,


*Hervé OBEJERO*


*Formateur TMO Post-Production / ProTools*
*Campus La Salle, ensemble scolaire Saint-Genès.*
*BORDEAUX TALENCE.*

Mail: herve.obejero@saint-genes.com

**Comment by Herve33** [comment]
Bonjour,


J'ai transféré votre demande à la personne en charge d'intégrer l'appli sur
notre réseau et voici sa réponse:

"
Bonjour,

Voici les noms des produits installés sur Windows Server 2012R2 :

httpd-2.4.25-x64-vc14-r1
php-7.1.1-Win32-VC14-x64
MySQL-installer-community-5.7.17.0

Le script utilisé pour le chargement de la base est BDD_default.sql

J'ai pu intervenir avec phpMyAdmin pour qu'il n'apparaisse plus d'erreur
sur champ sans valeur par défaut aussi pour les matériels et les
bénéficiaires.

Il reste l'erreur Ajax pour laquelle je relève des erreurs 500 avec le
debugger du navigateur. Les traces Apache sont en cohérence :

[13/Feb/2017:14:34:07 +0100] "GET /modals/personnel_add_techniciens.php
HTTP/1.1" 200 3713
[13/Feb/2017:14:34:07 +0100] "GET /fct/tekos_Ajax.js?_=1486992847582
HTTP/1.1" 200 9658
[13/Feb/2017:14:35:04 +0100] "POST /fct/tekos_actions.php HTTP/1.1" 500 -
[13/Feb/2017:14:35:55 +0100] "POST /fct/tekos_actions.php HTTP/1.1" 500 -

Les erreurs qui apparaissent :

[Mon Feb 13 14:35:04.160793 2017] [php7:error] [pid 9416:tid 1004] PHP
Fatal error:  Uncaught Exception: ERREUR SQL de Infos::save() :
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for
column 'birthDay' at row 1 in D:\\Robert\\Apache24\\htdocs\\
classes\\Infos.class.php:150\nStack trace:\n#0
D:\\Robert\\Apache24\\htdocs\\classes\\Tekos.class.php(79):
Infos->save('id', NULL)\n#1
D:\\Robert\\Apache24\\htdocs\\fct\\tekos_actions.php(23):
Tekos->save()\n#2 {main}\n  thrown in
D:\\Robert\\Apache24\\htdocs\\classes\\Infos.class.php
on line 150, referer: http://pedago-2012r2:83/index.php?go=gens
[Mon Feb 13 14:35:55.710944 2017] [php7:error] [pid 9416:tid 1004] PHP
Fatal error:  Uncaught Exception: ERREUR SQL de Infos::save() :
SQLSTATE[HY000]: General error: 1364 Field 'idUser' doesn't have a default
value in D:\\Robert\\Apache24\\htdocs\\classes\\Infos.class.php:150\nStack
trace:\n#0 D:\\Robert\\Apache24\\htdocs\\classes\\Tekos.class.php(79):
Infos->save('id', NULL)\n#1
D:\\Robert\\Apache24\\htdocs\\fct\\tekos_actions.php(23):
Tekos->save()\n#2 {main}\n  thrown in
D:\\Robert\\Apache24\\htdocs\\classes\\Infos.class.php
on line 150, referer: http://pedago-2012r2:83/index.php?go=gens

"

Et après des tests effectués depuis mon poste, j'ai relevé les erreurs
suivantes:

CALENDRIER
- impossible de créer des techniciens, donc impossible de créer des
évènements

MATÉRIEL
- ajout de matériel -> OK
- ajout de matériel sans date d'achat -> erreur SQL
- modification de matériel -> erreur AJAX

- modification des sous- catégorie -> erreur sur id

GENS
- ajout de technicien -> erreur AJAX

BÉNÉFICIAIRES
- ajout de bénéficiaire -> OK
- modification de bénéficiaire -> OK

INFOS
- modification des infos -> OK

SAUVEGARDE
- sauvegarde de la BDD -> OK


Encore merci beaucoup pour votre aide.

Bonne journée.



Cordialement,


*Hervé OBEJERO*


*Formateur TMO Post-Production / ProTools*
*Campus La Salle, ensemble scolaire Saint-Genès.*
*BORDEAUX TALENCE.*

Mail: herve.obejero@saint-genes.com

**Comment by polosson** [comment]
Bonjour,

Je pense que c'est dû à la version de MySQL installée. En effet la version 5.7 a introduit de nouveaux modes par défaut, qui induisent une utilisation des requêtes beaucoup plus stricte. Et Robert 1 a été conçu à l'époque de MySQL 5.5...

Une possibilité est donc de modifier les modes par défaut de MySQL.

ATTENTION cependant, ne faites cela que si vous utilisez MySQL pour Robert seulement ! Cela impacterai aussi vos autres éventuels outils utilisant MySQL, car c'est une modification de la configuration globale de MySQL. Pour modifier les modes, voici la requête faire depuis une console MySQL (connecté en tant que "root") :

`SET @@global.sql_mode= 'NO_ENGINE_SUBSTITUTION';`

Il devrait aussi être possible d'effectuer cette requête depuis phpMyadmin.

**Comment by moutew** [comment]
@polosson Le fichier default_bdd.sql n'a aucune définition de colonnes pouvant être nulles. Toutes sont NOT NULL, ce qui n'est pas le cas des champs facultatifs forcément.
Je suis en train de modifier le fichier, c'est étrange que ça ai marché sur d'autres installs ...

**Comment by fbastien** [comment]
@moutew À mon avis, le problème ne vient pas juste du fait que les colonnes des champs facultatifs soient NOT NULL, mais plutôt une histoire de mode strict comme dit @polosson. Car quand les champs ne sont pas renseignés, le Robert n'essaie pas d'insérer NULL ou la valeur par défaut, mais explicitement une chaîne de caractères vide (puisque c'est ce que retourne le formulaire HTML), et c'est là qu'il y a un soucis (cf. message d'erreur sur le birthDay). En mode "pas strict" (je sais pas s'il a un nom ^^), si on essaie d'insérer une chaîne vide dans un champ qui n'est pas de type texte, MySQL va l'accepter en remplaçant par la valeur par défaut implicite du type de la colonne. En revanche en mode strict il va refuser.
Je m'y connais pas trop dans les évolutions de MySQL, mais effectivement ça peut être qu'à un moment ils ont changé le mode par défaut, voire peut-être que la configuration par défaut n'est pas la même selon l'OS (mais là c'est juste une hypothèse, j'en sais rien).

Pour info, sur l'install que j'avais, par exemple si je ne mettais pas de date d'achat pour le matériel, une fois sauvegardé ça devenait '0000-00-00'.
Par contre attention, je crois que simplement rendre nullable les colonnes dans le schéma ne résout pas tous les problèmes, ou du moins ça en apporte d'autres. Sur mon fork, j'ai passé certains champs nullable, mais il me semble que du coup j'avais dû faire des modifs dans le code...

**Comment by moutew** [comment]
@fbastien Content de te revoir ! Exact, les chaînes vides passées en paramètres annulaient les valeurs nulles. Je viens d'ajouter la possibilité d'ajouter la valeur NULL en BDD dans la classe Infos qui gère toutes les opérations d'enregistrement. J'ai ajouté cette condition si on force la variable php à null. Je l'ai seulement forcé sur les champs de date qui posaient problème. 
J'ai quand même modifié certains champs qui sont facultatifs pour pouvoir les rendre null, même si pour tous les champs textes ce n'était donc pas problématique.

**Comment by moutew** [comment]
@Herve33 , après test sous windows et linux avec mysql 5.7 je pense que c'est réglé. il vous faudra mettre votre installation et votre schéma de BDD à jour. 
Si vous aviez fait des enregistrements il ne faudra pas passer par le menu sauvegarde, celui ci recréera la même structure. Utilisez plutôt l'interface de MySQL.
Avant cela vous devrez aussi sauvegarder votre fichier config/common.inc car il sera écrasé de la même façon.
Si cela résoud le problème je pourrais clore le bug.
N'hésitez pas à [participer au forum](http://robertforum.polosson.com/) et vous inscrire à la newsletter pour la deuxième version.

**Comment by Herve33** [comment]
Bonjour,

Merci infiniment pour votre aide et vos précieux conseils, presque TOUT
fonctionne maintenant.
Je vous transfère le dernier message que m'a envoyé notre informaticien

"
Bonjour,

J'ai intégré la requête proposée dans le script de création des tables de
la base de données et je l'ai ré-exécuté.
Toutes les tables ont ainsi été recréées.
J'ai pu recréer votre compte utilisateur sans avoir le moindre message
d'anomalie !
Je vous laisse refaire des tests. Je suis optimiste, maintenant !
"

Et après plusieurs tests que je viens d'effectuer, le seul point qui semble
encore poser problème est la modification des sous-catégorie -> impossible
de les renommer, d'en supprimer, par contre, je peux en créer!

Merci encore, grâce à vous le problème a été résolu à 99% en très de peu de
temps.

J'ai hâte de voir la v2.

Bon courage à vous tous.



Cordialement,


*Hervé OBEJERO*


*Formateur TMO Post-Production / ProTools*
*Campus La Salle, ensemble scolaire Saint-Genès.*
*BORDEAUX TALENCE.*

Mail: herve.obejero@saint-genes.com

**Comment by moutew** [comment]
Bonjour,
On avance ! concernant les sous catégories est ce que vous pourriez m'envoyer la requête et la réponse depuis le navigateur comme précédemment. Il y a un problème de chargement mais je ne parvient pas à voir le problème sans ces paramètres. Également pouvez vous tester la modification de l'ordre des sous categs ? Dans ce cas la requête est générée lorsque l'on clique sur le bouton "terminer" de la fenêtre. La page étant rechargée la requête disparait de l'outil de debbugage à moins de cliquer sur le bouton 'persistant'.
Merci.

**Comment by polosson** [comment]
Sauf avis contraire je ferme ce ticket car il est résolu.

**Comment by Herve33** [comment]
Bonjour,


oui, désolé, j'étais persuadé de vous avoir signifié la résolution de ce
cas.

Merci encore pour votre aide à tous.



Cordialement,


*Hervé OBEJERO*


*Formateur TMO Post-Production / ProTools*
*Campus La Salle, ensemble scolaire Saint-Genès.*
*BORDEAUX TALENCE.*

Mail: herve.obejero@saint-genes.com

2017-03-03 23:02 GMT+01:00 Paul MAILLARDET <notifications@github.com>:
