### ISSUE TITLE
Connaitre l'id de la désignation complète

### ISSUE THREAD

**Issue by DeeDeePac187** [RobertManager/robert#58]
Bonjour, J'aimerais connaitre id de la désignation complète pour l'ajouter dans la pages d'ajout de matériels sans une réservation.

j'ai donc ajouté une ligne dans plan_matos_list.php, mais je ne connait pas ce qui faut mettre à la place de $label

```
Ligne 130 –––– <div class='inline mid quart leftText pad30L matos_name' ext='$ext'>$label</div>
Ligne 131 –––– <div class='inline mid quart leftText pad30L matos_name' ext='$ext'>$matos</div>
```

Quelqu'un peux m'aider ? 

Merci

**Comment by DeeDeePac187** [comment]
Personnes ?

**Comment by polosson** [comment]
Bonjour,
Je ne comprend pas vraiment votre demande... Que voulez-vous afficher, en fait ? La variable `$matos` que vous citez ici n'est pas définie dans la boucle...

Si vous voulez simplement afficher l'ID du matériel, il faut remplacer votre `$matos` par `$id` à la ligne 131.

**Comment by DeeDeePac187** [comment]
Bonjour, 

Je souhaite avoir la désignation complète en plus de la référence.

Dans la colonne 130 il y a la ref
j'ai dupliqué cette ligne en 131 mais je ne connait pas le $??? correspondant à la désignation complète.

Merci de votre retour.

**Comment by polosson** [comment]
La désignation complète est appelée `label` dans la base de données.

Pour la récupérer, il faut :

- renommer la variable `$label` en  `$ref` à la ligne 106, et ajouter une ligne en dessous avec `$label`, comme ceci :

```php
106       $ref   = $v['ref'];
107       $label = $v['label'];
```
- ajouter la ligne 131 comme vous l'avez fait, en utilisant `$ref` et `$label`.

**Comment by polosson** [comment]
@DeeDeePac187 N'ayant pas eu de nouvelle de votre part, je considère que c'est résolu et je ferme la discussion.
