### ISSUE TITLE
Sauvegarde des infos de la société impossible

### ISSUE THREAD

**Issue by rts01** [RobertManager/robert#59]
Bonjour,

Je suis dirigeante d'une société de location de matériels audio.  
Recherchant un outils simple pour la gestion de notre parc, j'ai fait installer ROBERT par un informaticien.  
Je pense que le paramétrage est à faire.  
J'arrive bien a ouvrir le logiciel via une adresse internet propre mais 2 soucis se présentent :

- Impossible de sauvegarder la base de données...
- Le calendrier est grisé.

Par contre, je rentre mes techniciens sans problème, et ils restent bien dans le logiciel.  
Pourriez vous m'aider, car l'utilisation de cet outil serait vraiment parfait pour notre structure.

**Comment by polosson** [comment]
Bonjour,
Avez-vous ajouté du matériel et des packs de matériel ?

**Comment by rts01** [comment]
Bonjour,
oui, création pack matériel,technicien, bénéficiaires est resté enregistrer mais toujours pas de calendrier.
Le plus gros problème c'est qu'on ne peut pas enregistrer de modifications, infos société, sauvegarde Message : Impossible de sauvegarder la base de données....
Désolé pour la réponse tardive, un peu de boulot  grosse période d'activité.

**Comment by polosson** [comment]
J'imagine (vu le nom) que c'est vous que j'ai eu au téléphone ce soir même. Je récapitule ici, au cas où ce n'était pas vous, et pour que d'éventuelles personnes ayant le même problème puissent trouver la solution à l'avenir :

Les deux problèmes (impossibilité d'enregistrer les infos de la société, et accès impossible au calendrier) viennent du fait que les informations ne peuvent être enregistrées sur le serveur. En effet, ces données sont stockées dans un fichier sur le serveur (dans le dossier `config/`), et si ce dossier est inaccessible en écriture par Robert, il ne peut pas l'enregistrer. Et, tant que les informations de la société n'existent pas, le calendrier redirige automatiquement vers la modification de ces infos...

Il faudrait donc vous assurer que les dossiers de Robert, sur le serveur, sont accessibles en écriture pour l'utilisateur Apache (l'utilisateur du système linux nommé `www-data`, en général sur un debian), et notamment les dossiers `BFlogs/`, `config/`, et `datas/`.  
Dans l'idéal, ils devraient avoir les droits d'accès `0755` (en octal, ce qui donne `rwxr-xr-x`) et appartenir à l'utilisateur `www-data` et au groupe `www-data`.

Merci de bien vouloir confirmer ici même que le problème est résolu après avoir fait ces changements, et si ce n'est pas le cas, nous verrons plus avant.

**Comment by rts01** [comment]
Bonjour Polosson.
Un grand merci pour votre réponse, votre accueil et votre solution.
Robert fonctionne parfaitement.
Meilleures amitiés.
