### ISSUE TITLE
La page \"".$_GET['go']."\" n'existe pas !

### ISSUE THREAD

**Issue by ALC79** [RobertManager/robert#62]
Bonsoir Paul,

Suite a un upgrade xubuntu 16.04 vers 18.04 j'ai le message d'erreur suivant en lieu et place de la page d’accueil.

```
'; $page_admin = array ('calendrier', 'materiel', 'gens', 'beneficiaires', 'infos', 'sauvegarde' ); $page_users = array ('calendrier', 'materiel', 'gens', 'beneficiaires' ); $choose = array(); if ( $_SESSION['user']->isAdmin() ) $choose = $page_admin ; else $choose = $page_users ; foreach ( $choose as $k ){ $nomPage = $k; $classUi = 'default'; if (isset($_GET['go']) && @$_GET['go'] == $nomPage) $classUi = 'highlight'; elseif ((!isset($_GET['go']) || @$_GET['go'] == 'ajout_plan' || @$_GET['go'] == 'modif_plan') && $k == 'calendrier') $classUi = 'highlight'; echo "

".strtoupper($nomPage)."
"; } } ?> BugHunter

La page \"".$_GET['go']."\" n'existe pas !

RETOUR AU CALENDRIER
"; } else include ('pages/p_calendrier.php'); } ?> 
```

Avez-vous une idée?

Merci d'avance

Thierry

**Comment by polosson** [comment]
Il s'agit clairement d'un mauvais paramétrage de Apache (le logiciel-serveur) qui n'interprète pas le langage PHP. Pour remédier au problème, je vous suggère de réinstaller apache2 et php, utilisant une commande du genre :

```bash
sudo apt install -f apache2 php7.1 libapache2-mod-php7.1
```
Puis, activer le module php et relancer le serveur Apache:

```bash
sudo a2enmod php7.1 && sudo service apache2 restart
```
Si le problème persiste, il faut peut-être vérifier que les _balises php courtes_ sont activées dans le fichier `/etc/php5/apache2/php.ini`. Il s'agit du paramètre `short_open_tag` qu'il faut mettre à `=On`.

**Comment by ALC79** [comment]
Bonjour Paul,

Désolé pour la seconde issue. Ce n'était pas une relance, seulement une erreur de ma part car sur mon profil l'issue apparaissait pas et je n'étais pas sur qu'elle vous soit parvenue.

Pour le Robert tout semble être rentré dans l'ordre.
Merci pour vos conseils éclairés.
Juste un détail concernant la commande
(sudo apt install -f apache2 php7.2 libapache2-mod-php7.2) j'ai du remplacer php7.1 par php7.2 car la commande me renvoyait des erreurs

de même la commande (sudo a2enmod php7.2 && sudo service apache2 restart) me renvoyait les messages ci-dessous
Considering dependency mpm_prefork for php7.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.2:

je l'ai résolu avec la commande (systemctl restart apache2)

Encore merci pour cette belle application.

Thierry


PS y a t'il encore un lien pour l'aide au financement de la V2?



----- Mail original -----
De: "Paul MAILLARDET" <notifications@github.com>
À: "RobertManager/robert" <robert@noreply.github.com>
Cc: "ALC79" <alc79@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Samedi 8 Septembre 2018 11:04:11
Objet: Re: [RobertManager/robert] La page \"".$_GET['go']."\" n'existe pas ! (#62)



Il s'agit clairement d'un mauvais paramétrage de Apache (le logiciel-serveur) qui n'interprète pas le langage PHP. Pour remédier au problème, je vous suggère de réinstaller apache2 et php, utilisant une commande du genre : 
sudo apt install -f apache2 php7.1 libapache2-mod-php7.1 

Puis, activer le module php et relancer le serveur Apache: 
sudo a2enmod php7.1 && sudo service apache2 restart 

Si le problème persiste, il faut peut-être vérifier que les balises php courtes sont activées dans le fichier /etc/php5/apache2/php.ini . Il s'agit du paramètre short_open_tag qu'il faut mettre à =On . 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 

-- 
ALC79
8 chemin de champ-viron
79260 FRANÇOIS
Association loi 1901 depuis 2003
SIRET: 798 946 612 00016
APE 9002Z
Contact: +33 7 81 70 41 96
Courriel:alc79@free.fr
