### ISSUE TITLE
Plus d'accès suit a MISE A JOUR

### ISSUE THREAD

**Issue by ALC79** [RobertManager/robert#63]
Bonsoir Paul,

Suite a un upgrade xubuntu 16.04 vers 18.04 j'ai le message d'erreur suivant en lieu et place de la page d’accueil.

'; $page_admin = array ('calendrier', 'materiel', 'gens', 'beneficiaires', 'infos', 'sauvegarde' ); $page_users = array ('calendrier', 'materiel', 'gens', 'beneficiaires' ); $choose = array(); if ( $_SESSION['user']->isAdmin() ) $choose = $page_admin ; else $choose = $page_users ; foreach ( $choose as $k ){ $nomPage = $k; $classUi = 'default'; if (isset($_GET['go']) && @$_GET['go'] == $nomPage) $classUi = 'highlight'; elseif ((!isset($_GET['go']) || @$_GET['go'] == 'ajout_plan' || @$_GET['go'] == 'modif_plan') && $k == 'calendrier') $classUi = 'highlight'; echo "

".strtoupper($nomPage)."
"; } } ?> BugHunter

La page \"".$_GET['go']."\" n'existe pas !

RETOUR AU CALENDRIER
"; } else include ('pages/p_calendrier.php'); } ?> 

Avez-vous une idée?

Merci d'avance

Thierry

**Comment by polosson** [comment]
Bonjour, merci de ne __PAS__ re-créer des _issues_ quand on met du temps à répondre. Nous répondons quand on peut, ça ne sert à rien de nous relancer. Je ferme cette _issue_ et je répond à la première.
